spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  rsocket.server.port: 7000
  r2dbc:
    url: "r2dbc:postgresql://localhost/moeawebframework"
    username: "postgres"
    password: "postgres"

logging.level.org.springframework.data.r2dbc: DEBUG

minio:
  bucket: 'objects'
  accessKey: 'minioadmin'
  secretKey: 'minioadmin'
  endpoint: 'http://localhost:9000'

---

spring:
  profiles: prod
  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  #Redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

cdn_url: ${CDN_URI}
