spring:
  profiles:
    active: dev
  # Uploading files
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

---

spring:
  rsocket.server.port: 7000
  profiles: dev

logging.level.org.springframework.data.r2dbc: DEBUG

CDN_URI: 'localhost:8070'
R2DBC_URI: 'r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE'

---

spring:
  profiles: prod
  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  #Redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

CDN_URI: ${CDN_URI}
R2DBC_URI: ${R2DBC_URI}
