spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  rsocket.server.port: 7000
  r2dbc:
    # R2DBC_URI: 'r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE'
    url: "r2dbc:postgresql://localhost/moeawebframework"
    username: "postgres"
    password: "postgres"

logging.level.org.springframework.data.r2dbc: DEBUG

cdn_url: 'localhost:8070'

---

spring:
  profiles: prod
  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  #Redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

cdn_url: ${CDN_URI}
